### ISSUE TITLE
Install and Configure @husky, @lint-staged and @commitlint

### ISSUE THREAD

**Issue by gustavoabel** [meowtive/meowtive#12]
## **Why implement husky, lint-staged and commitlint? What are the advantages?**

- Commits Pattern
- Automated Test before the commit
- Git Flow Integration
- Code Pattern
- Error Signaling (Stage Area Files)
- Auto-correct

**more details:** [lint-staged](https://github.com/okonet/lint-staged), [husky](https://typicode.github.io/husky/#/)
**reference:** [styleguides](https://betterprogramming.pub/comparing-the-top-three-style-guides-and-setting-them-up-with-eslint-98ea0d2fc5b7)

**Comment by FilipiRafael** [comment]
Looking forward to implementing this one :)
